### ISSUE TITLE
cherrypicker stopped working

### ISSUE THREAD

**Issue by MigrantBirdd** [big-o/cherrypicker#5]
hello

i installed the cherrypick plugin for testing in my website, in advanced it worked very well but after less than of 24H, is completely down doesn’t work at all and after click on that for scrapping the page info, just shown the title of in a blank page; that’s it.
any guide to solve the problem please.

thanks a lot

**Comment by big-o** [comment]
Can you provide any more detail? Tracebacks, commands etc.

**Comment by big-o** [comment]
Closing as this sounds like an issue with a different piece of software with a similar name. Please feel free to reopen with more detail if I've misunderstood.
