### ISSUE TITLE
Delim parameter for flatten is not customizable

### ISSUE THREAD

**Issue by Aerilius** [big-o/cherrypicker#6]
The method signature of `CherryPickerMapping.flatten` implies that `delim` can be set to something else, for example very common delimiters like `.` or `/`.

- However, as a `@property`, arguments passed to it are ignored and don't override the default value. If it is intended that the delimiter can be overridden, `flatten` should not be a property.
- Secondly, the inner calls `cls._flatten(…)` miss the `delim` argument so that the overridden value would only be appended after the first key, whereas deeper keys get again the default delimiter.

**Test case:**  
```python
from cherrypicker import CherryPicker
CherryPicker({"outer": {"inner": {"innermost": "value"}}}).flatten(delim=".").get()
```

**Expected result:**  
`{'outer.inner.innermost': 'value'}`

**Actual result:**  
`{'outer_inner_innermost': 'value'}`

**Comment by big-o** [comment]
Thanks for spotting this oversight. Should be fixed in v0.4.0 now - I've opted for a breaking change to keep the interface clean since the userbase is small.
